# Generated by Django 5.2 on 2025-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
