# Generated by Django 5.2 on 2025-04-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Client')], max_length=10),
        ),
    ]
