# Generated by Django 5.2 on 2025-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('academic_formation', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('benefits1', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits2', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits3', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits4', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits5', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits6', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits7', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits8', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits9', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits10', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('inactive_status', models.CharField(blank=True, max_length=20)),
                ('date_of_dismissal_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
