# Generated by Django 5.2 on 2025-04-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0003_remove_employee_benefits1_remove_employee_benefits10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='benefits',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
