# Generated by Django 5.2 on 2025-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0002_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='benefits1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits10',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits6',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits7',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits8',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefits9',
        ),
        migrations.AddField(
            model_name='employee',
            name='benefits',
            field=models.ManyToManyField(to='rh_management.benefit'),
        ),
    ]
